#SPDX-License-Identifier: MIT-0
---
# tasks file for wordpress

- name: Install WordPess package list
  ansible.builtin.include_tasks: install.yaml
  tags: install
  when: ansible_facts["os_family"] == "Debian"

- name: Provision WordPress
  ansible.builtin.include_tasks: provision.yaml
  tags: configure
  when: ansible_facts["os_family"] == "Debian"