
- name: Copy Nginx config for wordpress
  ansible.builtin.template:
      src:  templates/nginxwordpress.j2         
      dest: /etc/nginx/sites-available/wordpress    
      owner: root                           
      group: root                           
      mode: '0644' 
  tags: [always] 

- name: Activate site for Nginx
  ansible.builtin.shell: |
     ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/
     systemctl reload nginx
  tags: [always] 

- name: Copy wp-config.php 
  ansible.builtin.template:
      src:   templates/wp-config.php.j2        
      dest: /var/www/wp-config.php   
      owner: root                           
      group: root                           
      mode: '0644' 
  tags: [always] 